apiVersion: v1
kind: Pod
metadata:
  name: logging-app
  labels:
    app: logging
spec:
  containers:
  - name: logging-container
    image: busybox
    command: ["sh", "-c", "while true; do echo logging; sleep 10; done"]
  nodeSelector:
    role: logging
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "logging"
    effect: "NoSchedule"

